version: "3"
services:
  nodeapp:
    container_name: node_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      WAIT_HOSTS: postgresql:5432
    networks:
      - node-webapp-network
  postgresql:
    container_name: postgresql
    image: postgres:16
    volumes:
      - ~/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge
